filesize_format = "B" # can be b, kb, kib, mb, mib, gb, gib, etc
skip_welcome_message = true
disable_table_indexes = false
nonzero_exit_errors = true
startup = [
 "mkdir ~/.cache/starship",
 "starship init nu | save ~/.cache/starship/init.nu",
 "source ~/.cache/starship/init.nu",			
 ""
]
prompt = "starship_prompt"
table_mode = "light"

[env]
SASCALL_DEFAULT_CONFIG="/home/datguy/Documents/SASCal/test/config.toml"
SASCALL_TEST_PROFILE="/home/datguy/Documents/SASCall/test/config.toml"
JULIA_COPY_STACKS=1 
_JAVA_AWT_WM_NONREPARENTING=1 # https://github.com/swaywm/sway/issues/595

[color_config]
primitive_int = "green"
primitive_decimal = "red"
primitive_filesize = "ur"
primitive_string = "pb"
primitive_line = "yellow"
primitive_columnpath = "cyan"
primitive_pattern = "white"
primitive_boolean = "green"
primitive_date = "ru"
primitive_duration = "blue"
primitive_range = "purple"
primitive_path = "yellow"
primitive_binary = "cyan"
separator_color = "purple"
header_align = "l" # left|l, right|r, center|c
header_color = "c" # green|g, red|r, blue|u, black|b, yellow|y, purple|p, cyan|c, white|w
index_color = "rd"
leading_trailing_space_bg = "white"

[line_editor]
max_history_size = 100000
history_duplicates = "ignoreconsecutive" # alwaysadd,ignoreconsecutive
history_ignore_space = false
completion_type = "circular" # circular, list, fuzzy
completion_prompt_limit = 100
keyseq_timeout_ms = 500 # ms
edit_mode = "emacs" # vi, emacs
auto_add_history = true
bell_style = "visable" # audible, none, visible
color_mode = "forced" # enabled, forced, disabled
tab_stop = 4

[textview]
term_width = "default" # "default" or a number
tab_width = 4
colored_output = true
true_color = true
header = true
line_numbers = true
grid = true
vcs_modification_markers = true
snip = true
#wrapping_mode = "NoWrapping" # Character, NoWrapping
use_italics = true
#paging_mode = "QuitIfOneScreen" # Always, QuitIfOneScreen, Never
theme = "Dracula"


